# Generated by Django 3.0.5 on 2020-04-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(max_length=2000, null=True)),
                ('year', models.IntegerField(null=True)),
                ('actores', models.TextField(max_length=2000, null=True)),
                ('duracion', models.IntegerField()),
                ('enCartelera', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PeliculasCategorias_categoria', to='app.Categoria')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PeliculasCategorias_pelicula', to='app.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=200)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentario_pelicula', to='app.Pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentario_usuario', to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificacion_pelicula', to='app.Pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificacion_usuario', to='app.User')),
            ],
        ),
    ]
