# Generated by Django 3.0.5 on 2020-04-29 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('dateHour', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(max_length=2000, null=True)),
                ('year', models.IntegerField(null=True)),
                ('cast', models.TextField(max_length=2000, null=True)),
                ('duration', models.IntegerField()),
                ('trailer', models.CharField(max_length=100)),
                ('onBillboard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_movie', to='app.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_user', to='app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='peliculacategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='peliculacategoria',
            name='pelicula',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='PeliculaCategoria',
        ),
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(to='app.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_movie', to='app.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_user', to='app.User'),
        ),
    ]
