# Generated by Django 3.0.5 on 2020-05-01 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200501_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
