# Generated by Django 3.0.5 on 2020-05-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_movie_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='creation_date',
        ),
    ]
